# Generated by Django 5.1.5 on 2025-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('complete', models.BooleanField(default=False, verbose_name='Completada')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
