# Generated by Django 5.1.5 on 2025-02-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('id_ciclo_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuestionarios.ciclos')),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('id_ciclo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.ciclos')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('id_cuestionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField()),
                ('id_pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.preguntas')),
            ],
        ),
    ]
