# Generated by Django 5.1.5 on 2025-02-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertadas', models.IntegerField()),
                ('falladas', models.IntegerField()),
                ('porcentaje_acierto', models.FloatField()),
                ('id_ciclo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.ciclos')),
                ('nombre_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.usuarios')),
            ],
        ),
    ]
