# Generated by Django 5.1.5 on 2025-02-23 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0002_estadisticas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='id_cuestionario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuestionarios.cuestionarios'),
        ),
    ]
