# Generated by Django 5.1.5 on 2025-02-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_estadisticas_id_cuestionario_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionarios',
            name='descripcion_cuestionario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='nombre_cuestionario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='nombre_usuario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.usuarios'),
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='tema_asignatura_cuestionario',
            field=models.TextField(null=True),
        ),
    ]
