# Generated by Django 5.1.5 on 2025-04-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_cuestionarios_descripcion_cuestionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionarios',
            name='id_asignatura_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.asignaturas'),
        ),
    ]
