# Generated by Django 5.1.5 on 2025-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_cuestionarios_id_asignatura_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='nombre_cuestionario',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
