<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-16 16:48

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1.5 on 2025-02-11 10:13

import django.db.models.deletion
import django.utils.timezone
>>>>>>> 1f322e2f831b8d0a1d643f6dc4d20b325f0186a3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 1f322e2f831b8d0a1d643f6dc4d20b325f0186a3
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='JefeProyecto',
            fields=[
                ('dni_jefe_proyecto', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_jefe', models.CharField(max_length=80)),
=======
            name='Empleados',
            fields=[
                ('dni_empleado', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='dni_empleado')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre_empleado')),
                ('jefe_proyecto', models.BooleanField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni_usuario', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre_usuario')),
>>>>>>> 1f322e2f831b8d0a1d643f6dc4d20b325f0186a3
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre_proyecto', models.CharField(max_length=80)),
                ('descripcion_proyecto', models.TextField()),
                ('proyecto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.jefeproyecto')),
                ('usuario', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
=======
                ('titulo', models.CharField(max_length=200, verbose_name='titulo_proyecto')),
                ('descripcion', models.TextField()),
                ('presupuesto', models.FloatField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha_inicio')),
                ('jefe_proyecto_fk', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.empleados', to_field='jefe_proyecto')),
                ('dni_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_proyecto_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyectos'),
        ),
>>>>>>> 1f322e2f831b8d0a1d643f6dc4d20b325f0186a3
    ]
