# Generated by Django 5.1.6 on 2025-02-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeProyecto',
            fields=[
                ('dni_jefe_proyecto', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_jefe', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=80)),
                ('descripcion_proyecto', models.TextField()),
                ('proyecto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.jefeproyecto')),
                ('usuario', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
