# Generated by Django 5.1.5 on 2025-02-11 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empleado', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='dni_empleado')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre_empleado')),
                ('jefe_proyecto', models.BooleanField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('dni_usuario', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo_proyecto')),
                ('descripcion', models.TextField()),
                ('presupuesto', models.FloatField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha_inicio')),
                ('jefe_proyecto_fk', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.empleados', to_field='jefe_proyecto')),
                ('dni_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_proyecto_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyectos'),
        ),
    ]
