# Generated by Django 5.1.5 on 2025-02-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='jefe_proyecto',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='jefe_proyecto_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.empleados'),
        ),
    ]
