# Generated by Django 5.1.6 on 2025-02-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='proyecto_fk',
            new_name='jefe_proyecto_fk',
        ),
    ]
