# Generated by Django 5.1.6 on 2025-02-16 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_proyecto_fk_proyectos_jefe_proyecto_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
